contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 8ca60145-186f-47d7-822f-b6737a63cf6f
inputs: []
name: data collection
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 68b90b66-8a94-4f2a-8d7e-b6ef6f4aba60
      iscommand: false
      name: ""
      version: -1
    taskid: 68b90b66-8a94-4f2a-8d7e-b6ef6f4aba60
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    form:
      description: ""
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: Do you like pancakes
        options: []
        optionsarg:
        - simple: "Yes"
        - simple: "No"
        placeholder: testset
        readonly: false
        required: false
        tooltip: test
        type: singleSelect
      sender: ""
      title: test
      totalanswers: 0
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body: null
      cc: null
      format: ""
      methods:
      - email
      subject:
        simple: test
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: true
        retriescount: 2
        retriesinterval: 360
      to:
        simple: Administrator
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 383e63a0-756c-43a4-807b-caf5902c6c8e
      iscommand: false
      name: data collection
      type: collection
      version: -1
    taskid: 383e63a0-756c-43a4-807b-caf5902c6c8e
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 450,
          "y": 370
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      seconds:
        simple: "5"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sleep for X seconds.
      id: c3066d15-d01b-4193-8163-19a083a2abe3
      iscommand: false
      name: sleep
      script: Sleep
      type: regular
      version: -1
    taskid: c3066d15-d01b-4193-8163-19a083a2abe3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1010,
          "y": 370
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a message to an Amazon SNS topic, a text message (SMS message)
        directly to a phone number, or a message to a mobile platform endpoint (when
        you specify the TargetArn ).
      id: 53f8d5ea-544c-42df-8810-2f928dfb6eb1
      iscommand: true
      name: Send SMS/Text
      script: '|||aws-sns-send-message'
      type: regular
      version: -1
    taskid: 53f8d5ea-544c-42df-8810-2f928dfb6eb1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1010,
          "y": 670
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 715,
        "width": 940,
        "x": 450,
        "y": 50
      }
    }
  }
