contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.0.0
    itemVersion: 4.0.0
    packID: Darktrace
    packName: Darktrace
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
deprecated: true
description: Deprecated. Use Darktrace Basic Model Breach Handler and Darktrace Basic
  AI Analyst Event Handler instead.
id: Handle Darktrace Model Breach
inputs: []
name: Handle Darktrace Model Breach
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "27"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 25d266d8-f022-44ac-8f93-9e4babbc1844
      iscommand: false
      name: ""
      version: -1
    taskid: 25d266d8-f022-44ac-8f93-9e4babbc1844
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 517.5,
          "y": 40
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      pbid:
        simple: ${incident.darktracemodelbreachid}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Darktrace-get-breach returns a model breach based on its model
        breach id (pbid)
      id: 0e2abde6-4c43-41dc-8b14-8c46ceb0f0b5
      iscommand: true
      name: Get Model Breach Details
      script: '|||darktrace-get-breach'
      type: regular
      version: -1
    taskid: 0e2abde6-4c43-41dc-8b14-8c46ceb0f0b5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 75,
          "y": 660
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body:
        simple: Would you like to Acknowledge this Model Breach in Darktrace?
      cc: null
      format: ""
      methods: []
      replyOptions:
      - "Yes"
      - "No"
      subject: null
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: false
        retriescount: 2
        retriesinterval: 360
      to: null
    nexttasks:
      "No":
      - "7"
      "Yes":
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Conditional
      id: 0cd5572d-33d0-4ce0-8309-e39cd702bbaa
      iscommand: false
      name: Acknowledge Model Breach?
      type: condition
      version: -1
    taskid: 0cd5572d-33d0-4ce0-8309-e39cd702bbaa
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 75,
          "y": 2485
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "17"
    note: false
    quietmode: 0
    scriptarguments:
      pbid:
        simple: ${incident.darktracemodelbreachid}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Acknowledge a model breach as specified by Model Breach ID
      id: 21482081-6f72-469f-88c4-b3d6a52632c6
      iscommand: true
      name: Acknowledge Model Breach
      script: '|||darktrace-acknowledge'
      type: regular
      version: -1
    taskid: 21482081-6f72-469f-88c4-b3d6a52632c6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -140,
          "y": 2660
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "31"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: Model breach not acknowledged.
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: f79f10c0-95ce-4d56-8784-8c35ecce4186
      iscommand: false
      name: Print Not Acknowledged
      script: Print
      type: regular
      version: -1
    taskid: f79f10c0-95ce-4d56-8784-8c35ecce4186
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 290,
          "y": 2660
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "29"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 03753539-091f-4c2b-8d41-4ce4cb4b9245
      iscommand: false
      name: Get Device Info
      type: title
      version: -1
    taskid: 03753539-091f-4c2b-8d41-4ce4cb4b9245
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 75,
          "y": 815
        }
      }
  "12":
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6be25a24-6323-42cf-8c1f-624f277ed89b
      iscommand: false
      name: Get Entity Info
      type: title
      version: -1
    taskid: 6be25a24-6323-42cf-8c1f-624f277ed89b
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 75,
          "y": 1450
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      Email:
        complex:
          accessor: Email.Address
          root: Account
          transformers:
          - operator: uniq
      Hostname:
        complex:
          accessor: hostname
          root: Darktrace.ModelBreach.device
          transformers:
          - operator: uniq
      IP:
        complex:
          accessor: ip
          root: Darktrace.ModelBreach.device
      ResolveIP:
        simple: "False"
      URL:
        complex:
          accessor: Data
          root: URL
          transformers:
          - operator: uniq
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: Enrich entities using one or more integrations.
      id: 7f4322cf-46ff-406d-85af-ca4022c43c3e
      iscommand: false
      name: Entity Enrichment - Generic v3
      playbookId: Entity Enrichment - Generic v3
      type: playbook
      version: -1
    taskid: 7f4322cf-46ff-406d-85af-ca4022c43c3e
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 75,
          "y": 1595
        }
      }
  "14":
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "26"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Finds similar incidents by common incident keys, labels, custom fields or context keys.
        It's highly recommended to use incident keys if possible (e.g., "type" for the same incident type).
        For best performance, it's recommended to avoid using context keys if possible (for example, if the value also appears in a label key, use label).
      id: fd416118-9383-44e9-8fcc-93db438d6537
      iscommand: false
      name: Find and Link Similar Incidents
      type: title
      version: -1
    taskid: fd416118-9383-44e9-8fcc-93db438d6537
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 75,
          "y": 1720
        }
      }
  "15":
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: builtin
      description: Link incidents together or mark them as duplicate and close them
      id: 9eaa894d-2c9c-4cd0-8947-1721bd971d79
      iscommand: false
      name: Acknowledge & Resolve Incident
      type: title
      version: -1
    taskid: 9eaa894d-2c9c-4cd0-8947-1721bd971d79
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 75,
          "y": 2360
        }
      }
  "17":
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "24"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 67abc5cf-14f8-4de7-8501-c86b5c4382ca
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 67abc5cf-14f8-4de7-8501-c86b5c4382ca
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 290,
          "y": 2955
        }
      }
  "18":
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "19"
    note: false
    quietmode: 0
    scriptarguments:
      max_results:
        simple: "5"
      order:
        simple: desc
      order_by:
        simple: lastSeen
      query:
        simple: ${incident.darktracedevicehostname}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Gets device identity information based on label, tag, type, hostname,
        ip, mac, vendor and os. It is recommended to run the command to check the
        relevant fields in context.
      id: 26c44e4c-6b83-4cef-8d84-ff8663334bb2
      iscommand: true
      name: Get Device Detail
      script: '|||darktrace-get-device-identity-info'
      type: regular
      version: -1
    taskid: 26c44e4c-6b83-4cef-8d84-ff8663334bb2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 75,
          "y": 1130
        }
      }
  "19":
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      did:
        simple: ${incident.darktracedeviceid}
      max_results:
        simple: "5"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns a list of similar devices to a device specified by Darktrace
        DID
      id: 8a65911a-5b0c-4265-8234-c873dfb36976
      iscommand: true
      name: List Similar Devices
      script: '|||darktrace-list-similar-devices'
      type: regular
      version: -1
    taskid: 8a65911a-5b0c-4265-8234-c873dfb36976
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 75,
          "y": 1275
        }
      }
  "20":
    continueonerrortype: ""
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c30e463f-c93a-469f-8781-727c983afd12
      iscommand: false
      name: Get Model Breach Info
      type: title
      version: -1
    taskid: c30e463f-c93a-469f-8781-727c983afd12
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 75,
          "y": 545
        }
      }
  "22":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: isSimilarIncidentFound
          operator: isEqualString
          right:
            value:
              simple: "true"
      label: "yes"
    continueonerrortype: ""
    id: "22"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "15"
      "yes":
      - "23"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Conditional
      id: cb340629-110b-460f-8cb5-a02686292c98
      iscommand: false
      name: Link Similar Incidents?
      type: condition
      version: -1
    taskid: cb340629-110b-460f-8cb5-a02686292c98
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 75,
          "y": 1990
        }
      }
  "23":
    continueonerrortype: ""
    id: "23"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      action:
        simple: link
      linkedIncidentIDs:
        simple: ${similarIncident.rawId}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Link incidents together or mark them as duplicate and close them
      id: e3bcc446-b57a-4f7c-8c3f-15727b9a35a4
      iscommand: true
      name: linkIncidents
      script: Builtin|||linkIncidents
      type: regular
      version: -1
    taskid: e3bcc446-b57a-4f7c-8c3f-15727b9a35a4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 290,
          "y": 2165
        }
      }
  "24":
    continueonerrortype: ""
    id: "24"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4276f614-41cc-44f0-866e-eddc09da5474
      iscommand: false
      name: Investigation Closed
      type: title
      version: -1
    taskid: 4276f614-41cc-44f0-866e-eddc09da5474
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 290,
          "y": 3080
        }
      }
  "26":
    continueonerrortype: ""
    id: "26"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    scriptarguments:
      hoursBack:
        simple: "1000"
      maxResults:
        simple: "10"
      similarIncidentKeys:
        simple: incident.darktracedeviceid
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Finds similar incidents by common incident keys, labels, custom fields or context keys.
        It's highly recommended to use incident keys if possible (e.g., "type" for the same incident type).
        For best performance, it's recommended to avoid using context keys if possible (for example, if the value also appears in a label key, use label).
      id: a8dfcd45-5eb6-4dd4-87b9-527b9775bcd7
      iscommand: false
      name: FindSimilarIncidents
      script: FindSimilarIncidents
      type: regular
      version: -1
    taskid: a8dfcd45-5eb6-4dd4-87b9-527b9775bcd7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 75,
          "y": 1835
        }
      }
  "27":
    continueonerrortype: ""
    id: "27"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "30"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1e62210a-141d-42a4-8983-20891943e3b6
      iscommand: false
      name: Check Integration Enabled
      type: title
      version: -1
    taskid: 1e62210a-141d-42a4-8983-20891943e3b6
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 517.5,
          "y": 185
        }
      }
  "29":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${incident.darktracedevicehostname}
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "29"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "12"
      "yes":
      - "18"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Conditional
      id: 46e1f2e4-12bc-40df-8e6d-2b446d26928d
      iscommand: false
      name: Does device exist?
      type: condition
      version: -1
    taskid: 46e1f2e4-12bc-40df-8e6d-2b446d26928d
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 75,
          "y": 940
        }
      }
  "30":
    continueonerrortype: ""
    id: "30"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "24"
      "yes":
      - "20"
    note: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: Darktrace
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      id: 6ee98514-519f-47db-8f09-3d5ef80d24c3
      iscommand: false
      name: Check Integration is enabled
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 6ee98514-519f-47db-8f09-3d5ef80d24c3
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 517.5,
          "y": 320
        }
      }
  "31":
    continueonerrortype: ""
    id: "31"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "17"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: This task is open as the Darktrace model breach is unacknowledged.
      id: 56f60ba9-07d9-439b-818a-4db8eb402957
      iscommand: false
      name: Analyst Manual Investigation
      type: regular
      version: -1
    taskid: 56f60ba9-07d9-439b-818a-4db8eb402957
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 290,
          "y": 2790
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 3105,
        "width": 1037.5,
        "x": -140,
        "y": 40
      }
    }
  }
