contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: Eskom - Splunk - Excessive Failed Logins VPN v2
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: f0e6b33d-1e43-4df9-806e-5588d36ef308
inputs:
- description: Username to enrich
  key: username
  playbookInputQuery: null
  required: false
  value: {}
name: Eskom - User Enrichment
outputs:
- contextPath: UsernamesNotFound
  type: unknown
- contextPath: UsernamesFound
  type: unknown
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 39a80149-1b81-46d3-8321-132e2b9086b2
      iscommand: false
      name: ""
      version: -1
    taskid: 39a80149-1b81-46d3-8321-132e2b9086b2
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      forEach: true
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 2
    scriptarguments:
      Username:
        complex:
          root: inputs.username
          transformers:
          - args:
              client_domain:
                value:
                  simple: eskom.co.za
            operator: 491831f2-ccd5-4fb5-83e9-a21dc099acaa
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Enrich accounts using one or more integrations.
        Supported integrations:
        - Active Directory
        - Microsoft Graph User
        - SailPoint IdentityNow
        - SailPoint IdentityIQ
        - PingOne
        - Okta
        - AWS IAM
        - Cortex XDR (account enrichment and reputation)

        Also, the playbook supports the generic command 'iam-get-user' (implemented in IAM integrations). For more information, visit https://xsoar.pan.dev/docs/integrations/iam-integrations.
      id: 7682524f-b2cf-4c02-8b1a-8d5654a6bff4
      iscommand: false
      name: Account Enrichment - Generic v2.1
      playbookId: Account Enrichment - Generic v2.1
      type: playbook
      version: -1
    taskid: 7682524f-b2cf-4c02-8b1a-8d5654a6bff4
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
  "2":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: Account.Email.Address
                    operator: containsGeneral
                    right:
                      iscontext: true
                      value:
                        simple: inputs.username
                root: Account
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 704f6826-d81a-4bad-811a-edc774205608
      iscommand: false
      name: Account found?
      type: condition
      version: -1
    taskid: 704f6826-d81a-4bad-811a-edc774205608
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "false"
      key:
        simple: Account.Input
      value:
        complex:
          root: inputs.username
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Set a value in context under the key you entered. If no value is entered, the script doesn't do anything.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.10/Cortex-XSOAR-Administrator-Guide/Automations
      id: 8e592959-24bb-40ac-81df-5abe4da52483
      iscommand: false
      name: Set provided username in the Account object
      script: SetAndHandleEmpty
      type: regular
      version: -1
    taskid: 8e592959-24bb-40ac-81df-5abe4da52483
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: UsernamesFound
      value:
        complex:
          root: inputs.username
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: c29205ba-a4a4-49c7-86dd-0a863a727940
      iscommand: false
      name: Append to the UsernamesFound object
      script: Set
      type: regular
      version: -1
    taskid: c29205ba-a4a4-49c7-86dd-0a863a727940
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: UsernamesNotFound
      value:
        complex:
          root: inputs.username
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: b65f436a-1cc0-4d31-8e6a-ab72bfccd9ee
      iscommand: false
      name: Append to the UsernamesNotFound object
      script: Set
      type: regular
      version: -1
    taskid: b65f436a-1cc0-4d31-8e6a-ab72bfccd9ee
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6ec66e1c-6b01-4ce3-8e49-608f8f8d45d4
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 6ec66e1c-6b01-4ce3-8e49-608f8f8d45d4
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 240,
          "y": 1130
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: "yes"
      keysToKeep:
        simple: UsernamesNotFound,UsernamesFound,Account
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.10/Cortex-XSOAR-Administrator-Guide/Automations
      id: dc3b2e79-357e-4db5-8758-900fdf5d2f67
      iscommand: false
      name: Delete context for the next interation
      script: DeleteContext
      type: regular
      version: -1
    taskid: dc3b2e79-357e-4db5-8758-900fdf5d2f67
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 230,
          "y": 940
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1145,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
